### ISSUE TITLE
the Tickled Username and Chat History are confused

### ISSUE THREAD

**Issue by EDGE-qy** [chenyifanthu/WechatAnnualReport#7]
When counting 年度热词, the user name appeared in tickling are counted. So for those chat groups with a lot of tickles, the top words may end up to be 拍了拍 or some user names, which is redundant and less fun.

**Comment by Xial-kotori** [comment]
This can be solved in PR #6 handle text messages only. I removed all non-text messages including tickle, invatation, gif emoji and so on.
